# Generated by Django 5.0.2 on 2024-03-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_des', models.TextField()),
                ('job_req', models.TextField()),
                ('work_loc', models.CharField(max_length=50)),
                ('app_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
