# Generated by Django 5.0.2 on 2024-03-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_title',
            field=models.TextField(),
        ),
    ]
