# Generated by Django 5.0.2 on 2024-03-09 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_jobdetails_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='job_sal',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
